package constants

const EmptySpace string = ""
const DSN string = "dsn"
const Uid string = "uid"
const Inside string = "Inside "
const RequestReadingError string = "Request Reading Error"
const QueryParamsMissingError string = "Query Params Missing"
const UnmarshalError string = "Failed to unmarshall the request"
const RequestRecieved string = "REQUEST RECEIVED "
const InvalidRequest string = "Invalid Request"
const DBConnectivityError string = "Failed to connect to database"
const Category string = "category"
const BaseURL string = "https://inshorts.com/api/en"
const UserAgent string = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
const CategoryAll string = "all_news"
const CategoryTop string = "trending_topics"
